site_name: MKDOCS_PROJECT
site_url: https://sitename.example
nav:
  - Home: index.md
  - About: about.md
theme:
  name:  readthedocs
  favicon: docs/img/favicon.ico
plugins:
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: true
